version: '3.9'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=juandevlop
      - POSTGRES_PASSWORD=postgres1
    ports:
      - '5432:5432'
    volumes:
      - /postgres_data:/var/lib/postgresql/data

volumes: 
  postgresql-volume:
    external: true
